name: release
permissions:
  contents: write

on:
  push:
    tags:
    - "v[0-9]+.*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Go
    - uses: actions/setup-go@v5
      with:
        go-version-file: '.go-version'
    - name: Generate github app token
      id: generate_github_app_token
      uses: tibdex/github-app-token@f717b5ecd4534d3c4df4ce9b5c1c2214f0f7cd06  # v1.6.0
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
        repository: minamijoyo/homebrew-hcledit
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: "~> v2"
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HOMEBREW_TAP_GITHUB_TOKEN: ${{ steps.generate_github_app_token.outputs.token }}
